닉네임(유저) 생성 기능 구현
woowacourse-teams/2021-babble pull request #195
Opened 2021-07-27 10:07 UTC by Hyeon9mak

## 🔥 구현 내용 요약
닉네임(유저) 생성 기능을 구현했습니다.

## ☠ 트러블 슈팅
- DTO `@Valid` 어노테이션 사용할 경우 별도 예외처리 핸들러로 잡아내도록 해야할 것 같습니다.
- 도메인 쪽 `@NonNull` 어노테이션을 붙일 경우 NullPointerException이 발생합니다.
  - 저희가 예상한 예외 이므로 핸들링 해야할 것 같은데, NullPointerException이라 애매합니다...
  - 다행히 lombok Config 파일을 지원한다고 하네요!

2021-07-27 10:59 UTC, unluckyjung commented on back/babble/src/test/java/gg/babble/babble/restdocs/UserApiDocumentTest.java
> +    }
이부분 들여쓰기가 깃헙상에서 굉장히 이상하게 보이는데 확인부탁드립니다.

2021-07-27 11:00 UTC, unluckyjung requested changes
코멘트 하나 남긴부분만 확인해주세요!
그외에는 별문제 없어보입니다.

2021-07-27 11:02 UTC, unluckyjung commented on back/babble/src/test/java/gg/babble/babble/restdocs/UserApiDocumentTest.java
> +    }
![image](https://user-images.githubusercontent.com/43930419/127143471-858e4c97-7a59-470b-9025-aef6cca1acb9.png)

변경전

![image](https://user-images.githubusercontent.com/43930419/127143408-9c5dee32-7342-4707-aa91-42c86dbb952a.png)

변경후

2021-07-27 12:06 UTC, lns13301 reviewed
🙅‍♂️

2021-07-27 12:06 UTC, lns13301 commented on back/babble/src/main/java/gg/babble/babble/controller/UserController.java
> +    public ResponseEntity<UserResponse> create(@Valid @RequestBody final UserRequest userRequest) {
PR 에 남긴 예상된 NullPointException 처리에 대해 제가 지금 생각나는 방법은 아래와 같습니다.

```java
    // UserController 클래스 내부
    @InitBinder("userRequest")
    private void initBind(WebDataBinder webDataBinder) {
        webDataBinder.addValidators(new UserValidator());
    }
```

```java    
// 따로 추가할 클래스
public class UserValidator implements Validator {
    @Override
    public boolean supports(Class<?> clazz) {
        return UserRequest.class.isAssignableFrom(clazz);
    }

    @Override
    public void validate(Object target, Errors errors) {
        UserRequest userRequest = (UserRequest) target;

        if (Objects.isNull(userRequest.getName())) {
            throw new BabbleNullPointException();
        }
    }
}
```

Validator 를 별도로 구현하여 도메인 로직을 검증 후 알맞은 커스텀 예외를 던지는 방법은 어떨까요?

2021-07-27 14:20 UTC, Hyeon9mak commented
- https://kafcamus.tistory.com/15
- https://www.baeldung.com/hibernate-notnull-vs-nullable
- https://www.baeldung.com/spring-boot-bean-validation

2021-07-27 14:25 UTC, Junroot commented
## `@NotNull`과 `@NonNull` 예외 처리를 ControllerAdvice에서 잡도록 수정하기

### `@NonNull` 의 경우

`@NonNull`는 만족하지 않으면 `NullPointerException`이 발생하는데 커스텀 예외를 던지게 구현할 수 없었다. 따라서 `@NotNull` 을 사용하도록 수정했다. Entity에 `@NotNull`을 추가하면 DDL에 NOT NULL 이 추가된다. 이 조건을 만족하지 못하면 `ConstraintViolationException` 가 터져서 별도로 잡을 수 있다.

### `@NotNull` 의 경우

기존에 DTO에 있던 `@NotNull`의 경우는 Spring MVC에서 이를 인식하여 `MethodArgumentNotValidException`를 던지게 된다. 따라서 `ControllerAdvice`에서 이 예외를 잡아주면 된다.

## 참고 자료

현구막과 동일

2021-07-28 04:17 UTC, unluckyjung approved these changes

2021-07-28 04:58 UTC, unluckyjung approved these changes

2021-07-28 04:59 UTC, merged

2021-07-28 05:02 UTC, lns13301 reviewed
코멘트 확인바랍니다.

2021-07-28 05:02 UTC, lns13301 commented on back/babble/src/main/java/gg/babble/babble/domain/user/User.java
> +    @NotNull(message = "닉네임은 Null 이어서는 안됩니다.")
메세지 일치 확인해주세요.