feat: 게임, 태그 한글 이름 구현
woowacourse-teams/2021-babble pull request #483
Opened 2021-09-03 12:55 UTC by Junroot

Closes #306 

## 🔥 구현 내용 요약

### API 수정

게임, 태그 한글이름을 구현하면서 아래의 API가 수정되었습니다. (api-docs 문서 기준)

**3.1. 게임 리스트 조회 API**

**3.2. 게임 단일 조회 API**

**3.5. 게임 등록 API**

**3.6. 게임 수정 API**

**5.1. 태그 전체 수신 API**

**4.1. 방 조회 API**

### 테스트 DB auto-ddl 수정

테스트 코드에서 flyway가 제대로 적용되었는지 확인하기 위해, `ddl-auto`를 `validate`로 수정했습니다.

## ☠ 트러블 슈팅

### @DataJpaTest 사용시 주의점

`@DataJpaTest` 를 사용하게 되면 `[application-test.properties](http://application-test.properties)` 같이 사용자가 구성해놓은 설정과는 별개로 동작하여 인메모리 DB인 H2를 사용하게 된다. 이런 자동 구성을 끄고, 내가 설정해놓은 구성을 사용하고 싶다면 `@AutoConfigureTestDatabase(replace=Replace.NONE)` 를 추가해야된다.

```java
@ActiveProfiles("test")
@Transactional
@DataJpaTest
@AutoConfigureTestDatabase(replace=Replace.NONE)
public class IssueRepositoryIntegrationTests
```

[https://stackoverflow.com/questions/53002232/spring-boot-datajpatest-unit-test-reverting-to-h2-instead-of-mysql](https://stackoverflow.com/questions/53002232/spring-boot-datajpatest-unit-test-reverting-to-h2-instead-of-mysql)

2021-09-04 05:22 UTC, Hyeon9mak requested changes
굿굿! 잘 봤어! 테스트도 잘 돌아가네!

`AlternativeGameNames`, `AlternativeTagNames` 일급컬렉션이나 
`AlternativeGameName`, `AlternativeGameNameRepository` 엔티티,
`AlternativeTagName`, `AlternativeTagNameRepository` 레퍼지토리

테스트가 많이 빠진거 같아!
이러면 다음에 루트의 코드를 리팩토링하는 사람이 테스트가 없어서 불안할거 같아.

그 부분에 대해서만 추가해주면 좋겠어요!

2021-09-04 05:22 UTC, Hyeon9mak commented on back/babble/src/main/java/gg/babble/babble/domain/game/Game.java
> +    }
꼼꼼한 편의 메서드 👍 

`addAlternativeName`에서 파라미터로 `AlternativeGameName`을 받았는데, 그 이름이 `name`이라서 

```java
if (hasName(name.getName()))
```

부분이 조금 부자연스럽게 느껴지는거 같아.
`hasName`과 `name` 모두 이름을 조금 더 직관적으로 바꿔보는거 어떨까?

2021-09-04 05:22 UTC, Hyeon9mak commented on back/babble/src/main/java/gg/babble/babble/domain/game/Games.java
> +}
오호. 뭔가 했더니 `GameService`에서 사용하는 일급컬렉션이구만? 👍 👍 👍

2021-09-04 05:22 UTC, Hyeon9mak commented on back/babble/src/main/java/gg/babble/babble/domain/room/Room.java
>      private Long id;
`Sessions`의 위치가 `id` 보다 낮게 내려왔으면 좋겠어!

2021-09-04 05:22 UTC, Hyeon9mak commented on back/babble/src/main/java/gg/babble/babble/domain/game/AlternativeGameNames.java
> +    private Set<AlternativeGameName> elements = new HashSet<>();
Set 사용 👍 👍 👍

2021-09-04 05:22 UTC, Hyeon9mak commented on back/babble/src/main/java/gg/babble/babble/domain/tag/Tag.java
> +
사실 이쯤되니 롬복을 쓰는 이유가 있나 싶기도 😂

2021-09-04 05:22 UTC, Hyeon9mak commented on back/babble/src/main/java/gg/babble/babble/domain/tag/TagName.java
> +        }
검증 메서드를 2개로 분리해서 생성자에서 2번 호출하면 눈에 더 잘 들어올거같아!

2021-09-04 05:22 UTC, Hyeon9mak commented on back/babble/src/main/java/gg/babble/babble/dto/request/GameRequest.java
> +
Null 일수도.. 있지 않을까?
그루밍 피터랑 이야기를 나눠봐야하는 부분일듯!

2021-09-04 05:22 UTC, Hyeon9mak commented on back/babble/src/main/java/gg/babble/babble/dto/response/CreatedRoomResponse.java
> +    private List<TagResponse> tags;
?! NoArgsConstructor가 붙는 순간 `CreatedRoomResponse`에 setter 메서드가 필요해지지않아?
final 키워드도 때게 되고... 어떤 이유에서 이렇게 한건지 궁금해!

2021-09-04 05:22 UTC, Hyeon9mak commented on back/babble/src/main/java/gg/babble/babble/domain/game/AlternativeGameNames.java
> +    }
이 부분에서 일급 컬렉션으로 감싼게 덜 활용되어서 조금 아쉬운거 같아.

일급 컬렉션은 `List`, `Set` 등의 컬렉션에게 단순한 컬렉션 이상의 역할을 부여하는거잖아?
그런데 `Game` 엔티티에선 `AlternativeGameNames` 일급 컬렉션을 일반 컬렉션과 동일하게 사용하고 있어!
`Set` 컬렉션에 이름만 부여된 느낌?!

`Game.hasName`이 기존 게임의 이름과 동일한지만 판단하고, `AlternativeGameNames` 중에 겹치는 이름이 있는지는
`AlternativeGameNames.add()`에서 검증하면 어떨까?

```java
// Game.java
    public boolean hasName(final String name) {
        return this.name.equals(name) || alternativeGameNames.contains(name);
    }
```
사실 이 녀석이 루트가 이렇게 구성하게 된 주 원인같긴해서... 나도 확신을 갖고는 이야기하기 어렵네 ㅎㅎ;

2021-09-04 07:21 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/controller/auth/DocsController.java
> +}
에고, 실수로 잘못된 패키지에 넣어버렸네 수정할게

2021-09-04 07:32 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/domain/game/Game.java
> +    }
`Game`의 이름은 `String`인데, 대체 이름의 타입은 `AlternativeGameName`이라 발생하는 문제인거같아.
이것도 `TagName`처럼 원시값 포장을 한번 해볼게

2021-09-04 07:36 UTC, lns13301 reviewed
대부분 현구막이 좋은 리뷰를 남겨줘서 크게 할건 안보이네
수고많았고, 피드백 반영까지 좀만 더 파이팅!

2021-09-04 07:36 UTC, lns13301 commented on back/babble/src/main/java/gg/babble/babble/domain/game/AlternativeGameNames.java
> +            .anyMatch(alternativeName -> alternativeName.getName().equals(name));
```suggestion
            .anyMatch(alternativeName -> alternativeName.isSameName(name));
```
이건 어떨까?!

2021-09-04 07:36 UTC, lns13301 commented on back/babble/src/main/java/gg/babble/babble/domain/game/AlternativeGameName.java
> +    @Id
애너테이션 달고 필드간 띄어쓰기가 없으니깐 식별이 잘 안되는 느낌이당..

2021-09-04 07:36 UTC, lns13301 commented on back/babble/src/test/java/gg/babble/babble/domain/GameTest.java
> +        final AlternativeGameName alternativeGameName = new AlternativeGameName("망겜", game);
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-09-04 07:57 UTC, Hyeon9mak commented on back/babble/src/test/java/gg/babble/babble/domain/GameTest.java
> +        final AlternativeGameName alternativeGameName = new AlternativeGameName("망겜", game);
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-09-04 08:02 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/domain/room/Room.java
>      private Long id;
이거 내가 의도한게 아닌데 코드 리포매팅하면 저절로 올라가네 왜지;;;

2021-09-04 08:11 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/domain/tag/TagName.java
> +        }
생각해보니 30~32라인은 `@NotNull` 어노테이션이 있어서 굳이 검증 안해도 될거같네!

2021-09-04 08:41 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/dto/request/GameRequest.java
> +
empty list일 순 있지만 null일수는 없지 않을까??

2021-09-04 08:50 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/domain/game/AlternativeGameNames.java
> +    }
`AlternativeGameNames.add()` 에도 검증은 있어도 좋긴한데, 결국엔 `Game`에서도 검증 부분이 있어야된다고 생각해.
그렇지않으면 단순히 `add()`메소드를 호출하다가 개발자 실수로 예외가 발생한건지, 개발자가 의도적으로 값을 가지고있으면 예외가 터지게 한건지 구분하기 힘들어서 둘다 있는게 좋을듯??

2021-09-04 08:55 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/domain/tag/TagName.java
> +        }
생각해보니 이건 `@NotNull` 어노테이션이 있으니 굳이 30~32번 줄은 필요없을 것 같네!

2021-09-04 08:59 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/dto/response/CreatedRoomResponse.java
> +    private List<TagResponse> tags;
잠깐 ObjectMapper 쓸 일이 있어서 전부 NoArgsConstructor 추가해줬는데, DTO의 경우는 NoArgsConstructor 유지해도 문제 없을 것 같아서, 그냥 유지했어.

2021-09-05 05:26 UTC, Hyeon9mak approved these changes
변경된거 확인했어!! 👍 👍 💯 🥇 
코멘트 몇 개 남겼으니 확인해주면 땡큐!!

2021-09-05 05:26 UTC, Hyeon9mak commented on back/babble/src/main/java/gg/babble/babble/domain/admin/Ip.java
> +    @NotNull
`@NotNull` 예외 메세지!

2021-09-05 05:26 UTC, Hyeon9mak commented on back/babble/src/main/java/gg/babble/babble/dto/request/GameRequest.java
> +
비워두면 무조건 empty list로 날아와?? 나는 여태 프론트가 보내기 나름인줄..

2021-09-05 05:26 UTC, Hyeon9mak commented on back/babble/src/main/java/gg/babble/babble/dto/request/GameRequest.java
> +        return game;
DTO의 toEntity() 살짝 로직을 품게 되는 느낌.. 🥲 
alternativeNames와 관계 때문에 어쩔 수 없나...?

혹시 `Game`객체에 정적 팩터리 메서드로 이걸 숨겨보는건 어때?

2021-09-05 05:26 UTC, Hyeon9mak commented on back/babble/src/main/java/gg/babble/babble/dto/response/ExitResponse.java
난 역시 이게 좋아 👍

2021-09-05 05:26 UTC, Hyeon9mak commented on back/babble/src/test/java/gg/babble/babble/domain/game/AlternativeGameNameTest.java
> +    void constructAlternativeGameName() {
꼼꼼한 테스트 아주 나이스해요옹!!!! 👍 👍 👍 💯

2021-09-05 05:26 UTC, Hyeon9mak commented on back/babble/src/test/java/gg/babble/babble/domain/repository/RoomRepositoryTest.java
> +@AutoConfigureTestDatabase(replace = Replace.NONE)
오, 처음보는 어노테이션인데 뭐야?

2021-09-05 05:26 UTC, Hyeon9mak commented on back/babble/src/test/resources/application-test.properties
> +spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
내 PR이랑 이부분 컨플릭트 날수도.
`flyway.enabled=true`로 변경했네?

2021-09-05 05:42 UTC, Junroot commented on back/babble/src/test/resources/application-test.properties
> +spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
flyway sql 제대로 작성했는지 테스트 코드에서 확인하려고 수정함!

2021-09-05 05:43 UTC, Junroot commented on back/babble/src/test/java/gg/babble/babble/domain/repository/RoomRepositoryTest.java
> +@AutoConfigureTestDatabase(replace = Replace.NONE)
>### @DataJpaTest 사용시 주의점
> 
> `@DataJpaTest` 를 사용하게 되면 `[application-test.properties](http://application-test.properties)` 같이 사용자가 구성해놓은 설정과는 별개로 동작하여 인메모리 DB인 H2를 사용하게 된다. 이런 자동 구성을 끄고, 내가 설정해놓은 구성을 사용하고 싶다면 `@AutoConfigureTestDatabase(replace=Replace.NONE)` 를 추가해야된다.
> 
> ```java
> @ActiveProfiles("test")
> @DataJpaTest
> @AutoConfigureTestDatabase(replace=Replace.NONE)
> public class IssueRepositoryIntegrationTests
> ```
> 
> [https://stackoverflow.com/questions/53002232/spring-boot-datajpatest-unit-test-reverting-to-h2-instead-of-mysql](https://stackoverflow.com/questions/53002232/spring-boot-datajpatest-unit-test-reverting-to-h2-instead-of-mysql)

이거 이슈 때문에 추가했어!

2021-09-05 05:46 UTC, merged