백엔드 로깅 파일 분리 추가 리팩토링
woowacourse-teams/2021-babble pull request #484
Opened 2021-09-04 10:47 UTC by Hyeon9mak

Closes #211 

## 🔥 스프링 프로필 분리
기존 prod, local, test 에서 prod, dev, local, test 로 분리했습니다.

- prod: main 브랜치에 해당. 프로덕션 서버용
- dev: release 브랜치에 해당. 개발용 서버용
- local: 말 그대로 개개인별 PC 환경에서 직접 테스트 해보는 용
- test: 테스트 코드 실행시 돌아가는 프로필

<br>

## 🔥 Logger와 Appender 분리
![image](https://user-images.githubusercontent.com/37354145/132091084-83ac3fba-680e-4e5d-a517-8d165bec9856.png)

### Logger - access와 spring으로 분리
- `logback-access.xml`: HTTP access 로깅
- `logback-spring.xml`: spring 내부 DEBUG~ERROR 레벨 로깅 + DB SQL 로깅
  - `logback-db.xml` 로도 분리하고 싶었는데, Logback이 네임추론에서 `db`를 읽지 못함 😭 
 
### Appender - console과 file로 분리
#### console
- `console-access-appender.xml`
  - `console-access-appender`: 콘솔에 출력할 HTTP access 로깅 포맷
- `console-db-appender.xml`
  - `console-db-sql-appender`: SQL 쿼리문 포맷
  - `console-db-value-appender`: SQL BasicBinder, BasicExtractor (SQL 쿼리문에 `?`로 표시되는 값 나타내는 그것) 포맷
- `console-log-appender.xml`
  - `console-log-appender`: gg.babble, org.springframework 등 Logger 에서 두루두루 쓰는 포맷 (TRACE~ERROR 레벨표시)

#### file
- `file-access-appender.xml`
  - `file-access-appender`: 파일로 저장할 HTTP access 로깅 포맷
- `file-debug-appender.xml`
  - `file-debug-appender`: 파일로 저장할 DEBUG 레벨 로깅 포맷
- `file-info-appender.xml`
  - `file-info-appender`: 파일로 저장할 INFO 레벨 로깅 포맷
- `file-warn-appender.xml`
  - `file-warn-appender`: 파일로 저장할 WARN 레벨 로깅 포맷
- `file-error-appender.xml`
  - `file-error-appender`: 파일로 저장할 ERROR 레벨 로깅 포맷

<br>

## 🔥 `@ActiveProfiles("test")` 중복코드 제거

```yml
# src/test/resources/application.yml
spring:
  profiles:
    active: test
```

위 파일 추가로 `src/main/resources/application-test.yml` 이 동작하도록 설정 할 수 있었습니다.

<br>

## ☠ 함께 고민해볼 사항 - 1. DB SQL 로깅은 콘솔에서만
며칠 전 제이슨 톡방에서 이야기했던 것처럼, "프로덕션 서버에서 DB SQL을 로깅하는게 옳은가?" 에 대해 고민해봤어요.
그러다 2가지 이유가 떠올라 DB SQL 로그는 파일 없이 콘솔로만 남기게 해보았습니다.

1. 초기엔 프로덕션 서버에서 저장하는 DB SQL 비즈니스적으로 가치가 있는 데이터라 생각했는데
비즈니스적으로 가치 있는 행동은 Http Access 로깅에서 이미 다 드러나고 있었고, 
DB SQL 로그는 조금 더 세세한 정보들일 뿐이라서 저장되는 로그파일 용량 대비 큰 효용성이 있는가 의심이 생겼어요.

2. '프로덕션 환경 데이터베이스 쿼리가 로그에 찍히는거 자체가 개인정보침해의 위험이 있지 않을까?' 를 떠올렸어요.
너잘은 이 의견에 대해 "애초에 프로덕션 서버 DB SQL을 왜 로깅해? 그거 개인정보침해 아냐?" 라는 반응이더라구요.

또, 조앤이 공유해준 링크에서도 DB SQL자체를 찍는 것보다, 에러에 대해서만 로깅하라고 하는 내용이 있었어요.
https://thorben-janssen.com/hibernate-logging-guide/

<br>

## ☠ 함께 고민해볼 사항 - 2. 로깅 레벨 정책
현재 우선은 스프링프로필 별로 로깅 레벨을 아래와 같이 맞춰두었어요.

- prod: INFO
- dev: DEBUG
- local: DEBUG
- test: DEBUG

이 과정에서 'prod가 굳이 INFO(예상된 에러)까지 로깅해야하나?', 'dev가 DEBUG까지 로깅해야하나?' 라는 고민이 들었습니다.
dev의 경우 개발용이니까 DEBUG까지 보는게 유의미 할 수 있겠지만, prod까지 그럴 필요는 있나? 싶긴 하네요.
warn이나 error까지 레벨을 변경해도 괜찮지 않을까 제안해볼게요!!

<br>

## ☠ 함께 고민해볼 사항 - 3. 로그 파일 관리 정책
로그 파일을 압축해서 관리하는 것도 좋지만, 압축 해놓을 경우 잘 읽지 않을거 같아 압축해서 저장하지 않도록 했어요. (쏘리 와일더 ㅠㅠ..)
빠른 시일 내에 일정 기간이 지난 로그파일은 S3로 전송하는 인프라를 구성해보는게 어떤가 싶어요!

2021-09-08 15:43 UTC, Junroot requested changes
현구막이 고생해준 덕분에 로그 파일 보기도 훨씬 편하고, 좀 더 편안하게 디버깅 할 수 있을듯!!👍👍👍

일단, conflict 나는 상황이니 Request changes로 둘게! 피드백 확인해보고 이야기 나눌 부분 있으면 더 나눠보자! 충돌해결하면 한번 더 리뷰 요청해줘!

2021-09-08 15:43 UTC, Junroot commented on back/babble/src/main/resources/application-dev.yml
> +    url: jdbc:mariadb://172.17.0.2:3306/babble
dev 환경에서 db가 docker로 운영되고 있어서 url이 자주 바뀌어서 굳이 명시할 필요가 없을 것 같긴하네.
우리 배포 환경의 경우에도 docker로 url이 자주 바뀌어서 지금은 저렇게 인자로 설정하는 방식을 쓰고 있어.

![image](https://user-images.githubusercontent.com/4648244/132537178-f62acad5-5d13-4441-8fe4-f9ba11a74119.png)

2021-09-08 15:43 UTC, Junroot commented on back/babble/src/main/resources/application-local.yml
> +    url: jdbc:h2:mem:testdb
```java
jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
```
h2의 datasource url 경우에는 위처럼 설정값을 추가하는게 좋다고 생각해!

DB_CLOSE_DELAY, DB_CLOSE_ON_EXIT은 h2가 의도치 않게 저절로 연결이 끊기는 경우가 있어서 설정해주는 값이야!
MODE는 h2가 mysql 방언을 사용할 수 있도록 해주는 설정!

2021-09-08 15:43 UTC, Junroot commented on back/babble/src/main/resources/application-test.yml
> +    url: jdbc:h2:mem:testdb
여기도 마찬가지!

2021-09-08 15:43 UTC, Junroot commented on back/babble/src/test/java/gg/babble/babble/controller/ApplicationWebSocketTest.java
> -@ActiveProfiles("test")
코드가 간결해졌다!! 👍

2021-09-08 15:43 UTC, Junroot commented on back/babble/src/main/resources/application-test.yml
> +    enabled: false
현재 develop 브랜치에는 flyway가 제대로 확인하는 용도로 `ddl-auto` 값을 `validate`로 바꿨어!

```properties
spring.flyway.enabled=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
```

거기에 따라 다음 값이 변경되기도 했고! 이거는 아마 conflict 해결하면서 수정할 것 같네!

2021-09-08 15:43 UTC, Junroot commented on back/babble/src/main/resources/logback/file-appender/file-error-appender.xml
> +      <fileNamePattern>${home}error-%d{yyyyMMdd}-%i.log</fileNamePattern>
이건 팀원들끼리 추가적으로 이야기할 필요가 있을 거 같은데, 나는 굳이 로그 레벨별로 파일을 분리할 필요가 있을지 고민이 되긴해 🤔

파일이 분리되어 있어서 전체 레벨의 로그 흐름을 보기 힘들다는 생각도 들고 ㅠㅠ cloudwatch에서 레벨 별로 필터링 해주는 기능 있는 걸로 알고 있어서 다시 합쳐보는 건 어떨지 생각해봐야될듯!

2021-09-08 15:43 UTC, Junroot commented on back/babble/src/main/resources/logback-spring.xml
>    </springProfile>
내 컴퓨터가 문제인지는 모르겠는데, test에서 모든 레벨에 대한 로그를 찍으니 테스트 코드 돌릴때 엄청 느려지는 문제가 있네 😰
개발용 서버에는 한번에 많은 요청이 들어오는 db레벨 찍어도 상관없는데, 테스트에서는 빼는게 좋지 않을까 싶어. 이건 좀 더 이야기해봐야될듯!

2021-09-09 03:37 UTC, Hyeon9mak commented on back/babble/src/main/resources/application-dev.yml
> +    url: jdbc:mariadb://172.17.0.2:3306/babble
노출된다는 것도 썩 좋은거 같지 않아. 당장은 기존 설정을 유지했어. 별도의 회의가 필요할거 같음!

2021-09-09 05:11 UTC, Hyeon9mak commented on back/babble/src/main/resources/application-local.yml
> +    url: jdbc:h2:mem:testdb
굳!! 바로 적용!!

2021-09-09 05:20 UTC, Hyeon9mak commented on back/babble/src/main/resources/logback/file-appender/file-error-appender.xml
> +      <fileNamePattern>${home}error-%d{yyyyMMdd}-%i.log</fileNamePattern>
`file-{level}-appender.xml` 파일을 분리한 이유는 설정들이 지나치게 길기 때문이었어!!

appender 는 display(로그 파일을 어떤 형식으로 저장할 것인지) 방법에만 초점이 맞춰진 파일이라 로그의 흐름은 `logback-spring.xml`을 확인하면 되겠지 싶긴 한데... 루트가 그렇게 이야기하니 고민되네 😢

2021-09-09 05:30 UTC, Hyeon9mak commented on back/babble/src/main/resources/logback-spring.xml
>    </springProfile>
루트가 피드백줬던 설정에 문제가 있는거 같아..
`url: jdbc:h2:mem:testdb; DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL`
이 설정 없이 테스트를 동작시키면 9초만에 끝나!!

![image](https://user-images.githubusercontent.com/37354145/132627964-eefd2482-c692-4325-bc3c-0cc04aa7fa2d.png)

또, 테스트에서 특히 모든레벨(TRACE 제외)을 찍어봐야 하지 않을까?!
테스트 단계에서 세세한 정보를 확인하면서 프로그램 완성도를 높히는게 맞지 않나 싶어!!
(개발용 서버에 올리고 나서야 DB 오류를 잡아내면 다시 PR쏘고 또 릴리즈에 올리고...)

2021-09-09 06:09 UTC, Hyeon9mak commented on back/babble/src/main/resources/application-test.yml
> +    enabled: false
오케이!! 이것도 적용!!

2021-09-09 06:27 UTC, lns13301 commented on back/babble/src/main/resources/logback-spring.xml
>    </springProfile>
나는 18초 나옴

2021-09-09 06:30 UTC, lns13301 commented on back/babble/src/main/resources/logback/file-appender/file-error-appender.xml
> +      <fileNamePattern>${home}error-%d{yyyyMMdd}-%i.log</fileNamePattern>
게임에서 예상치 못하게 아이템이 지급된 경우가 있다고 가정해 보자
그러면 잘못 아이템이 지급된 정보는 Info 레벨 정도겠지? 예외가 터졌다면 지급되지 않았을테니...
그렇기 때문에 prod 레벨에서는 Info 레벨까지 로깅하는게 맞는거 같아
그리고 이런 상황에서 Error 와 Error 가 아닌 것들을 구분해서 로그를 관리하려고 레벨별 분리를 했는데, 구구가 말하길 레벨별 분리를 왜하냐는 계속된 질문에 모르겠다... 🥺

2021-09-09 06:33 UTC, Hyeon9mak commented
Conflict 해결하고 피드백 준 내용들에 답글 달아뒀어!! 확인 부탁쓰!!!

2021-09-09 06:51 UTC, Junroot commented on back/babble/src/main/resources/logback/file-appender/file-error-appender.xml
> +      <fileNamePattern>${home}error-%d{yyyyMMdd}-%i.log</fileNamePattern>
>file-{level}-appender.xml 파일을 분리한 이유는 설정들이 지나치게 길기 때문이었어!!
>
> appender 는 display(로그를 어떤 형식으로 저장할 것인지) 방법에만 초점이 맞춰진 파일이라 로그의 흐름은 logback-spring.xml을 확인하면 되겠지 싶긴 한데... 루트가 그렇게 이야기하니 고민되네 😢

아 `xml` 파일을 레벨별로 분리한 이유를 물은건 아니였어! `.log` 파일이 굳이 레벨별로 분리될 필요가 있는가에 대한 질문이었다!

2021-09-09 06:53 UTC, Junroot commented on back/babble/src/main/resources/logback-spring.xml
>    </springProfile>
![image](https://user-images.githubusercontent.com/4648244/132637205-d5437dd3-c919-49b0-8e7c-dd5bfa09c02f.png)

나도 테스트 실행시간은 짧게 나오는데 뭔가 테스트 시작전에 로딩이 좀 걸리더라구 ㅇ.ㅇ

2021-09-09 06:54 UTC, Junroot approved these changes

2021-09-09 06:54 UTC, Junroot commented on back/babble/src/main/resources/application-test.yml
> +      replace: NONE
이거 되는게 짱 신기하네 ㄷㄷ

2021-09-09 06:54 UTC, merged

2021-09-09 07:03 UTC, Hyeon9mak commented on back/babble/src/main/resources/logback/file-appender/file-error-appender.xml
> +      <fileNamePattern>${home}error-%d{yyyyMMdd}-%i.log</fileNamePattern>
> 게임에서 예상치 못하게 아이템이 지급된 경우가 있다고 가정해 보자
> 그러면 잘못 아이템이 지급된 정보는 Info 레벨 정도겠지? 예외가 터졌다면 지급되지 않았을테니...

으엥??! `예상치 못하게 잘못 지급` 되는 건 우리 로깅 정책에서 `ERROR`, `WARN` 수준인건데,
`INFO`로 기록이 된다는 건 로깅 정책을 따르지 않았거나, 예외처리를 꼼꼼히 하지 못한거 아닐까?!?!?!

> 그렇기 때문에 prod 레벨에서는 Info 레벨까지 로깅하는게 맞는거 같아

물론 `INFO`레벨을 통해서 에러를 잡아내면 좋겠지만!!
'정상적으로 아이템이 지급되는 모든 경우'에 대해서도 로그가 엄청 쌓일텐데, 과연 그 로그 덩어리 속에서 '예상치 못하게 잘못 지급'된 에러를 찾아낼 수 있을지 고민되긴해...

> 그리고 이런 상황에서 Error 와 Error 가 아닌 것들을 구분해서 로그를 관리하려고 레벨별 분리를 했는데, 구구가 말하길 레벨별 분리를 왜하냐는 계속된 질문에 모르겠다... 🥺

로깅을 하는 이유가 사용자의 서비스 이용 흐름을 눈으로 읽고, 그 과정에서 발생하는 에러를 추적하기 위함이잖아?
그런데 ERROR, WARN, INFO가 다 나뉘어 있으면 3개의 파일을 다 열어보고 시간대를 비교해보면서 서비스 이용의 흐름을 파악해야겠지?
또, ERROR 파일만 참고해서 에러를 수정하면 그와 연관되는 서비스들에 사이드이펙트가 발생하는 걸 발견하기 힘들거고.
(이 부분에 대해서 초기 기획단계에서도 어필했었는데 레벨별로 나누자는 의견들이 워낙 확고해서... 😭 )
그래서 구구가 '그에 반해 레벨 별 분리를 했을 때 얻는 이점은 무엇이냐?' 라는 의도로 질문하신게 아닌가 싶네.