feat: 이미지 저장 기능 구현
woowacourse-teams/2021-babble pull request #519
Opened 2021-09-11 16:52 UTC by Junroot

Closes #511

## 🔥 구현 내용 요약

이미지 요청 API를 통해 이미지를 x1920, x1280, x640으로 리사이징하여 S3에 저장하는 기능을 구현했습니다.

파일 업로드시에 HTTP multipart를 사용하는 것이 좋다고 판단하여 API 수정이 있습니다.

![image](https://user-images.githubusercontent.com/4648244/132954846-ede634b9-7cce-4fa4-aaec-193d603e20aa.png)

자세한 내용은 rest docs의 아래 내용을 참고하면 됩니다.

- 6.1. 이미지 파일 전체 조회 API
- 6.2. 이미지 저장 API

## ☠ 트러블 슈팅

### Spring with AWS S3

다른 크루들의 이야기를 들어보니 Spring과 S3 연결이 access key 가 없어도 된다고해서 시도해보고 있습니다. Spring 애플리케이션이 AWS의 EC2에 부여한 IAM 권한을 이용해서 S3와 연결이 가능하다고 합니다.

![image](https://user-images.githubusercontent.com/4648244/132954904-cb182aec-05b8-42f8-80b6-287013ec2b81.png)

#### 의존성 추가

이것 저것 찾아다니면서 의존성 추가를 시도해봤는데 테스트가 전부 터지거나 의존성 추가에 실패했습니다. Spring 공식문서 방식대로 하니 다행이 잘 동작했습니다.

```groovy
implementation 'org.springframework.cloud:spring-cloud-aws-context:2.2.6.RELEASE'
```

#### 접근 권한

AWS 자원들에 접근 권한을 얻기 위해서는 아래의 과정을 순서대로 거쳐서 만족하면 됩니다. 5번의 경우가 내가 사용하려고 하는 접근 권한 얻는 방법입니다. 따라서 다음과 같이 accees key를 설정하지 않도 다음과 같은 방법으로 객체를 만들어 줄 수 있습니다.

![image](https://user-images.githubusercontent.com/4648244/132954912-10f8268b-a7d6-4b39-8abe-fcf6ccdd7b84.png)

#### 참고 자료

[https://docs.aws.amazon.com/ko_kr/sdk-for-java/v1/developer-guide/setup-credentials.html](https://docs.aws.amazon.com/ko_kr/sdk-for-java/v1/developer-guide/setup-credentials.html)

### 이미지 리사이징 및 압축

내용이 너무 많이 때문에 노션 링크로 대체합니다.
<https://iodized-capri-aa0.notion.site/a9bfa815e9cb436e9f26903782d3da1f>

### 개인 PC에서는 S3에 접근하지 못해 테스트에 실패하는 문제

이를 해결하기 위해서 ssh 터널링 등의 방법을 시도해봤지만, 테스트 속도가 현저하게 느려지는 문제가 있어서 결국 profile이 local일 때는 `InMemoryS3Repository`를 사용하도록 했습니다. 앞으로 개인 PC에서 테스트를 하거나 애플리케이션을 실행할 때는 profile을 local로 설정하는 것을 잊지 않아야 됩니다.

IntelliJ에서 테스트 코드 실행시 profile 설정하는게 잘 적용이 안되는 문제가 있는 아래의 사진처럼 설정하면 됩니다.

![image](https://user-images.githubusercontent.com/4648244/132955137-c8b639e5-b1da-4c30-9f69-178004d5bb7c.png)

Environment variables로 설정할 수 있습니다.

### Spring rest docs: Mockmvc에서 body 내용 수정하기

multipart 를 통해 파일을 body로 보내는데, 이미지라서 바이트 데이터로 보내게 됩니다. 

![image](https://user-images.githubusercontent.com/4648244/132955242-4d9df8ab-eb8f-4f42-a9d7-5fbc7bbd97ba.png)

rest-docs에서는 이를 굳이 보여줄 필요가 없기 때문에, body내용을 바꾸는 기능이 필요했다. 이를 위해서는 `preprocessRequest` 라는 것을 사용하면 됩니다.

```java
// MockMvc 테스트 중에
.andDo(document("save-image",
		preprocessRequest(new ImageBodyPreprocessor()),
		responseFields(
		    fieldWithPath("[]").description("파일 경로"))));
```

[링크 참고](https://github.com/woowacourse-teams/2021-babble/blob/001f2b51e8312ddaa9f881a82dff1fba5d64fbeb/back/babble/src/test/java/gg/babble/babble/restdocs/preprocessor/ImageBodyPreprocessor.java)

위 코드와 같이 file이라는 part의 내용을 수정해야 됐습니다.

![image](https://user-images.githubusercontent.com/4648244/132955252-d35a6953-e239-4ce2-82e8-ea482502a5b0.png)

위 결과와 같이 바이트 데이터대신 '<<binary data>>'라는 문자가 보이도록 수정했습니다.

#### 참고 자료

[https://stackoverflow.com/questions/60677805/mask-headers-in-spring-restdocs](https://stackoverflow.com/questions/60677805/mask-headers-in-spring-restdocs)

2021-09-12 03:25 UTC, Hyeon9mak commented
고생했슈! 👍 👍 👍  곧바로 코드 리뷰를 진행하기엔 백엔드끼리 지식 공유가 안된 부분이 많아서 별도로 회의를 해야할거 같아!!

2021-09-12 03:27 UTC, Junroot commented
> 고생했슈! 👍 👍 👍 곧바로 코드 리뷰를 진행하기엔 백엔드끼리 지식 공유가 안된 부분이 많아서 별도로 회의를 해야할거 같아!!

굳굳! 새롭게 다루게 된 부분이 많아서 아마, PR 메시지만으로는 이해하기 힘든부분이 있을 것 같네! 나중에 한 번 이야기 해보는 걸로!

2021-09-13 14:27 UTC, unluckyjung commented
**앞으로 개인 PC에서 테스트를 하거나 애플리케이션을 실행할 때는 profile을 local로 설정하는 것을 잊지 않아야 됩니다.** 
이부분 놓치면 안되겠네요. 이 PR은 따로 노션같은곳에 기록해놔야겠어요. 수고하셨슴당

2021-09-14 00:33 UTC, lns13301 commented
트러블 슈팅, 개발 내역 정리를 잘해놔서 이해가 잘됐음!! 👍
상세한 학습은 직접 해보면 좋겠지만 어떤식으로 현재 프로젝트에 적용되었는지는 알겠음! 😊
수고 많았네 진짜 👍

2021-09-14 05:37 UTC, unluckyjung submitted a review, later dismissed

2021-09-15 01:52 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/controller/ImageController.java
> +    public ResponseEntity<Set<String>> saveImage(@RequestParam("file") final MultipartFile file, @RequestParam("fileName") String fileName) {
불필요한 `Set`보다는 `List`을 사용하는게 좋다.
중복을 걸러내는 작업이 필요한게 아니다.

2021-09-15 01:55 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/domain/FileName.java
> +        final String[] simpleNameAndExtension = fullName.split(FILE_EXTENSION_DELIMITER, SPLIT_SIZE);
`final` 굳이 있어야될까요?

2021-09-15 01:59 UTC, Hyeon9mak commented on back/babble/src/main/java/gg/babble/babble/controller/ImageController.java
> +        return ResponseEntity.ok(imageService.saveImage(file, fileName));
컨트롤러에서만 봐도 내부 동작을 유추할 수 있도록 네이밍이 조금 더 상세하면 어떨까?!

2021-09-15 01:59 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/domain/image/ImageResolver.java
> +            param.setCompressionQuality(1.0f);
```suggestion
            param.setCompressionQuality(QUALITY);
```

상수화

2021-09-15 02:00 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/domain/image/ImageResolver.java
> +}
메소드 중 일부는 별도의 클래스로 분리하는게 좋지 않을까요

2021-09-15 02:03 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/domain/image/ImageResolver.java
> +    private ImageSize calculateSizeContaining(final ImageSize originalSize, final Integer maxPixel) {
해당 메서드는 `ImageSize` 안에 들어가도 괜찮지 않을까요?

2021-09-15 02:04 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/domain/repository/s3repository/DefaultS3Repository.java
> +    public Set<String> findAllImages() {
`Set`

2021-09-15 02:06 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/domain/repository/s3repository/DefaultS3Repository.java
> +        objectMetadata.setContentType(URLConnection.guessContentTypeFromName(fileName));
가독성을 위해 개행을 추가하면 좋을듯

2021-09-15 02:06 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/domain/repository/s3repository/InMemoryS3Repository.java
> +    public Set<String> findAllImages() {
`Set` to `List`

2021-09-15 02:07 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/service/ImageService.java
> +    private static final List<Integer> SAVED_SIZE = Arrays.asList(1920, 1280, 640);
`enum` 으로 관리해도 좋을듯!

2021-09-15 02:07 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/service/ImageService.java
> +    public Set<String> findAllImages() {
`Set` to `List`

2021-09-15 02:07 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/service/ImageService.java
> +    public Set<String> saveImage(final MultipartFile file, final String fullFilename) {
`Set` to `List`

2021-09-15 02:07 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/service/ImageService.java
> +    private Set<String> resizeAndSaveImage(final ImageResolver imageResolver, final FileName fileName) {
`Set` to `List`

2021-09-15 02:07 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/service/ImageService.java
> +        Set<String> savedImages = new HashSet<>();
`Set` to `List`

2021-09-15 02:09 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/service/ImageService.java
> +            final String newFileName = String
`final`

2021-09-15 02:10 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/service/ImageService.java
> +            final String newFileName = String
로직을 도메인단으로 숨길 수 있지 않을까. 고민 ㄱ

2021-09-15 02:12 UTC, Junroot commented on back/babble/src/test/java/gg/babble/babble/domain/repository/S3RepositoryTest.java
> +        final Set<String> allImages = s3Repository.findAllImages();
`Set` to `List`

2021-09-15 02:12 UTC, Junroot commented on back/babble/src/test/java/gg/babble/babble/domain/repository/S3RepositoryTest.java
> +        final Set<String> allImages = s3Repository.findAllImages();
`Set` to `List`

2021-09-15 02:12 UTC, Junroot commented on back/babble/src/test/java/gg/babble/babble/domain/repository/S3RepositoryTest.java
> +        final ClassLoader classLoader = getClass().getClassLoader();
`final`

2021-09-15 07:56 UTC, unluckyjung requested changes
아~주 사소한 피드백 몇개 남겼습니다 확인해주시고 다시 요청 ㄱ_ㄱ

2021-09-15 07:56 UTC, unluckyjung commented on back/babble/src/main/java/gg/babble/babble/domain/image/ImageResolver.java
> +    private static final float COMPRESSION_QUALITY = 1.0f;
`DEFAULT_EXTENSION` 이친구는 눈에 안들어왔었는데 아래꺼 변경사항이랑 같이 지금보니까 
**private**여도 충분하겠네요.
이미지 타입을.. 나중에 여러개 쓴다면 Enum으로 관리할만한 상수로 보이기도 합니다.

2021-09-15 07:56 UTC, unluckyjung commented on back/babble/src/main/java/gg/babble/babble/domain/image/ImageSize.java
> +        return this.multiply(resultRatio);
this는 없어도 괜찮겠네요.

2021-09-15 08:24 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/domain/image/ImageResolver.java
> +    private static final float COMPRESSION_QUALITY = 1.0f;
그렇네요! 수정하겠습니다!

2021-09-15 08:32 UTC, unluckyjung approved these changes
LGTM

2021-09-15 09:05 UTC, Hyeon9mak approved these changes
고생했슈!!!! 👍 👍 🥇  
확실히 오전에 코드 설명을 한 번 듣고 나니까 술술 이해가 되네!!!

귀찮겠지만 상수처리 부분에 대해서만 조금 남겨봤어!!
적용해주면 땡큐!!

2021-09-15 09:05 UTC, Hyeon9mak commented on back/babble/src/main/java/gg/babble/babble/domain/image/MutableImage.java
> +    }
`drawImage` 메서드는 라이브러리가 제공하는 메서드겠지..? `null`을 주입하는 걸 보고 깜짝 놀라서.. `null`을 주입할 수 밖에 없다면, 어떤 의미로 주입되는 `null`인지 상수처리 해주는 것도 괜찮을거같아!

2021-09-15 09:05 UTC, Hyeon9mak commented on back/babble/src/main/java/gg/babble/babble/service/ImageService.java
> +    }
이 피드백은 이건 귀찮을테니 당장은 X!!
다음에 한 번 리팩토링을 구상할 때 우리 프로젝트 전체에 일급컬렉션을 여기저기 적용해보면 좋겠다 싶네!!
ImageService도 다이어트 할듯!

2021-09-15 12:23 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/domain/FileName.java
> +        return new FileName(simpleNameAndExtension[SIMPLE_NAME_INDEX], simpleNameAndExtension[EXTENSION_INDEX]);
음 일부러 2개로 잘리도록 의도한 거긴해.
`abc.123.jpg`라고 하면 실제로 OS 상에서도 `jpg` 파일로 인식이 되거든!
근데 그걸 유도하려면 제일 뒤에있는 `.`를 잘라야 되는데 그게 안되고있네! 수정해볼게!

2021-09-15 12:38 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/domain/image/MutableImage.java
> +    }
저기 null 부분들은 필요없는 경우 null을 입력하라고 하길래 null을 넘기는 중이야! 상수화 할게!

2021-09-15 12:38 UTC, Junroot commented on back/babble/src/main/java/gg/babble/babble/service/ImageService.java
> +    }
이 부분도 어느정도 리팩토링 하려고했는데 45번 라인 때문에 어떻게 도메인으로 숨길지 애매하더라구 ㅋㅋㅋ
일단 패스~

2021-09-16 02:09 UTC, Hyeon9mak approved these changes

2021-09-16 02:09 UTC, Hyeon9mak commented on back/babble/src/main/java/gg/babble/babble/domain/FileName.java
> +        return new FileName(simpleName, extension);
:+1:

2021-09-16 02:10 UTC, merged