feat: 게임 관리 컴포넌트 구현
woowacourse-teams/2021-babble pull request #571
Opened 2021-10-01 17:38 UTC by ddongule

Closes #

## 😎 캡쳐본(프론트)
<img width="578" alt="Screen Shot 2021-10-02 at 2 35 03 AM" src="https://user-images.githubusercontent.com/26598561/135663251-26da9fce-f004-4582-bafd-72eea0d4375e.png">

## 🔥 구현 내용 요약
- 게임 관리 컴포넌트 구현
- 게임을 불러오는 로직 구현
- 게임 onClick시 게임의 데이터가 input들에 넣어질 수 있도록 구현
- 조회된 데이터가 없을 경우에 대한 alert를 추가

## ☠ 트러블 슈팅
- 따로 없었습니다!

2021-10-01 18:03 UTC, ddongule commented on front/src/chunks/GameManagement/GameManagement.scss
> +}
요 부분은 Global Style로 만들어두고 가져다 사용하거나, Mixin으로 빼도 좋을 것 같아요! 
관리자 컴포넌트에서 indent를 주고싶을 때 자주 사용하게 될 것 같아서 한 번 제안드려 봅니다 ㅎㅎ

2021-10-04 07:12 UTC, iborymagic requested changes
잘 구현하신 듯!!

2021-10-04 07:12 UTC, iborymagic commented on front/src/chunks/GameManagement/GameManagement.js
> +      (game) => game.name === selectedGame
이름으로 게임을 찾지 않고, id로 찾는 것이 더 좋아보여요!

2021-10-04 07:12 UTC, iborymagic commented on front/src/chunks/GameManagement/GameManagement.scss
> +}
좋은 생각인 것 같습니다! class보다는 mixin이 훨씬 좋아보여요.

2021-10-04 09:34 UTC, ddongule commented on front/src/chunks/GameManagement/GameManagement.scss
> +}
e247f1ef281a104a6a33ea52e1ac6581c1ccc6b5 에 반영했습니다!

2021-10-04 09:35 UTC, ddongule commented on front/src/chunks/GameManagement/GameManagement.js
> +      (game) => game.name === selectedGame
말씀주신대로 중복 가능성이 있는 이름으로 게임을 찾는 것 보다는, 고유한 id 값으로 게임을 찾는 것이 합리적이겠네요!
2148cd79d512472b58d176d0530391e400c9d9e2 에 반영했습니다!

2021-10-04 09:45 UTC, iborymagic approved these changes

2021-10-04 09:45 UTC, merged